# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iblx6vvHrCly_oUKw_bp670qmKbcDUj_
"""

#===========================================================
#    Text to Image using LoRA
#===========================================================

!pip install -q accelerate>=0.16.0 diffusers

import matplotlib.pyplot as plt
from diffusers import StableDiffusionPipeline
import torch

model_id = "Docty/naturo_lora"

# load model and scheduler
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16)
pipe.unet.load_attn_procs(model_id)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")


pipe.enable_attention_slicing()

# run pipeline in inference (sample random noise and denoise)
prompt = "A naruto with green eyes and red legs."
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5)

image.images[0]

plt.figure(figsize=(2,2))
plt.imshow(image['images'][0])